### ISSUE TITLE
"Conversion failed!`" only on specific anime video files

### ISSUE THREAD

**Issue by SquadCraftFTW** [mikigal/Anime4K-GUI#16] opened 2024-05-03 14:51 UTC
**Settings:** 
Target Resolution: 1920*1080
Anime Mode A+A
AV1 (CPU)
CRF: 21
Output format: MKV
Compatibility mode: OFF
Debug Mode: OFF

**Specs:**
Ryzen 5800x
32GB RAM
RTX 3070

**Issue:**
Conversion failing Anime, Add files, press start but get the error below. I have tried changing resolution, upscaling modes, encoder, CRF and output format and it still occurs. This issue occurs on all [Ember] transcodes and works fine with everything else. I have also tried without parsec, the same issue occurs. 

**Log:**

Version: Anime4K-GUI (1.1.1)
Authors: mikigal (whole app + FFMPEG tweaks), Ethan (core FFMPEG stuff)
Special thanks to bloc97 for Anime4K shaders
Drag n' drop your video files into this window (supported extensions: mp4, avi, mkv)

[15:47:58] Detected GPUs (3): 
[15:47:58]   1. Parsec Virtual Display Adapter
[15:47:58]   2. Meta Virtual Monitor
[15:47:58]   3. NVIDIA GeForce RTX 3070
[15:47:58] Available GPU acceleration: CUDA + NVENC
[15:48:07] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 17.mkv
[15:48:07] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 01.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 02.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 03.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 04.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 05.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 06.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 07.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 08.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 09.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 10.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 11.mkv
[15:48:08] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 12.mkv
[15:48:09] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 13.mkv
[15:48:09] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 14.mkv
[15:48:09] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 15.mkv
[15:48:09] Added file E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 16.mkv
[15:48:25] Processing [EMBER] Dungeon Meshi - 17.mkv (1 / 17)...

[15:48:28] Critical error occurred, upscaling has been stopped
[15:48:28] Please make issue on GitHub with logs, upscaling settings and your computer specification

[15:48:28] FFMPEG Error:
[15:48:28] exit status 0xfffffff4

[15:48:28] Critical error occurred, upscaling has been stopped
[15:48:28] Please make issue on GitHub with logs, upscaling settings and your computer specification

[15:48:28] FFMPEG logs:
[15:48:28] Input #0, matroska,webm, from 'E:\Plex\Media\TV Shows\Delicious in Dungeon\[EMBER] Dungeon Meshi - 17.mkv':
  Metadata:
    title           : S01E17-Harpy / Chimera
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2024-04-25T16:51:27.000000Z
  Duration: 00:25:31.95, start: 0.000000, bitrate: 2746 kb/s
  Chapters:
    Chapter #0:0: start 1.001000, end 91.008000
      Metadata:
        title           : Intro
    Chapter #0:1: start 91.008000, end 1440.983000
      Metadata:
        title           : Scene 1
    Chapter #0:2: start 1440.983000, end 1531.947000
      Metadata:
        title           : Credits
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)
      Metadata:
        title           : Presented By EMBER
        BPS             : 1975354
        DURATION        : 00:25:31.947000000
        NUMBER_OF_FRAMES: 36730
        NUMBER_OF_BYTES : 378267380
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-04-25 16:51:27
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
      Metadata:
        BPS             : 384000
        DURATION        : 00:25:30.912000000
        NUMBER_OF_FRAMES: 47841
        NUMBER_OF_BYTES : 73483776
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-04-25 16:51:27
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(jpn): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s
      Metadata:
        BPS             : 384000
        DURATION        : 00:25:30.912000000
        NUMBER_OF_FRAMES: 47841
        NUMBER_OF_BYTES : 73483776
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-04-25 16:51:27
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip (default) (forced)
      Metadata:
        title           : Forced
        BPS             : 0
        DURATION        : 00:21:24.659000000
        NUMBER_OF_FRAMES: 2
        NUMBER_OF_BYTES : 51
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-04-25 16:51:27
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(eng): Subtitle: subrip
      Metadata:
        BPS             : 61
        DURATION        : 00:25:08.924000000
        NUMBER_OF_FRAMES: 393
        NUMBER_OF_BYTES : 11589
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-04-25 16:51:27
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(eng): Subtitle: subrip
      Metadata:
        title           : SDH
        BPS             : 91
        DURATION        : 00:24:01.315000000
        NUMBER_OF_FRAMES: 537
        NUMBER_OF_BYTES : 16451
        _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-04-25 16:51:27
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:6: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 400x545 [SAR 96:96 DAR 80:109], 90k tbr, 90k tbn (attached pic)
      Metadata:
        filename        : cover.jpg
        mimetype        : image/jpeg
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> av1 (libsvtav1))
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
  Stream #0:3 -> #0:3 (copy)
  Stream #0:4 -> #0:4 (copy)
  Stream #0:5 -> #0:5 (copy)
  Stream #0:6 -> #0:6 (mjpeg (native) -> av1 (libsvtav1))
Press [q] to stop, [?] for help
[swscaler @ 000001f54485e000] deprecated pixel format used, make sure you did set range correctly
    Last message repeated 3 times
Unable to submit command buffer: VK_ERROR_DEVICE_LOST
[hwupload @ 000001f545326740] Failed to allocate frame to upload to.
[vf#0:0 @ 000001f53fe06900] Error while filtering: Cannot allocate memory
[vf#0:0 @ 000001f53fe06900] Task finished with error code: -12 (Cannot allocate memory)
[vf#0:0 @ 000001f53fe06900] Terminating thread with return code -12 (Cannot allocate memory)
[vost#0:0/libsvtav1 @ 000001f539de8000] Could not open encoder before EOF
[vost#0:0/libsvtav1 @ 000001f539de8000] Task finished with error code: -22 (Invalid argument)
[vost#0:0/libsvtav1 @ 000001f539de8000] Terminating thread with return code -22 (Invalid argument)
Unable to submit command buffer: VK_ERROR_DEVICE_LOST
[vf#0:6 @ 000001f543617680] Task finished with error code: -12 (Cannot allocate memory)
[vf#0:6 @ 000001f543617680] Terminating thread with return code -12 (Cannot allocate memory)
[vost#0:6/libsvtav1 @ 000001f53a063b40] Could not open encoder before EOF
[vost#0:6/libsvtav1 @ 000001f53a063b40] Task finished with error code: -22 (Invalid argument)
[vost#0:6/libsvtav1 @ 000001f53a063b40] Terminating thread with return code -22 (Invalid argument)
[out#0/matroska @ 000001f5429fbc40] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lq=0.0 size=       0kB time=N/A bitrate=N/A speed=N/A    
Conversion failed!

**Comment by mikigal** [comment] 2024-05-03 16:18
The problem is related to stream #0:6.
 It's a JPEG image embedded into the input file (probably a thumbnail or something), and the app tries to convert it using a video codec (libsvtav1in this case). 
I will make the fix soon.

**Comment by mikigal** [comment] 2024-05-03 16:33
@SquadCraftFTW 
Please upload video on Google Drive or similar and contact with me on Discord (mikigal) or mail (mikigal.priv@gmail.com).
I need file for testing

**Comment by SquadCraftFTW** [comment] 2024-05-03 16:45
> @SquadCraftFTW Please upload video on Google Drive or similar and contact with me on Discord (mikigal) or mail ([mikigal.priv@gmail.com](mailto:mikigal.priv@gmail.com)). I need file for testing

https://drive.google.com/drive/folders/1IBG9WQIweGv9mlPjRKJkeU0mQiZo4EJo?usp=drive_link

**Comment by SquadCraftFTW** [comment] 2024-05-03 16:46
Will send the link in a moment

**Comment by mikigal** [comment] 2024-05-04 14:18
Fixed in https://github.com/mikigal/Anime4K-GUI/commit/459ae18d5278756a352796e7e665e7910e50cfda

**Closed by mikigal** 2024-05-04 14:18 UTC
